CREATE TABLE IF NOT EXISTS `mtsequipment` (
  `inventoryequipmentid` bigint(20) UNSIGNED NOT NULL,
  `inventoryitemid` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `upgradeslots` int(11) NOT NULL DEFAULT 0,
  `level` int(11) NOT NULL DEFAULT 0,
  `str` int(11) NOT NULL DEFAULT 0,
  `dex` int(11) NOT NULL DEFAULT 0,
  `int` int(11) NOT NULL DEFAULT 0,
  `luk` int(11) NOT NULL DEFAULT 0,
  `hp` int(11) NOT NULL DEFAULT 0,
  `mp` int(11) NOT NULL DEFAULT 0,
  `watk` int(11) NOT NULL DEFAULT 0,
  `matk` int(11) NOT NULL DEFAULT 0,
  `wdef` int(11) NOT NULL DEFAULT 0,
  `mdef` int(11) NOT NULL DEFAULT 0,
  `acc` int(11) NOT NULL DEFAULT 0,
  `avoid` int(11) NOT NULL DEFAULT 0,
  `hands` int(11) NOT NULL DEFAULT 0,
  `speed` int(11) NOT NULL DEFAULT 0,
  `jump` int(11) NOT NULL DEFAULT 0,
  `ViciousHammer` tinyint(4) NOT NULL DEFAULT 0,
  `itemEXP` int(11) NOT NULL DEFAULT 0,
  `durability` int(11) NOT NULL DEFAULT -1,
  `enhance` tinyint(4) NOT NULL DEFAULT 0,
  `potential1` int(11) NOT NULL DEFAULT 0,
  `potential2` int(11) NOT NULL DEFAULT 0,
  `potential3` int(11) NOT NULL DEFAULT 0,
  `potential4` int(11) NOT NULL DEFAULT 0,
  `potential5` int(11) NOT NULL DEFAULT 0,
  `socket1` int(11) NOT NULL DEFAULT -1,
  `socket2` int(11) NOT NULL DEFAULT -1,
  `socket3` int(11) NOT NULL DEFAULT -1,
  `incSkill` int(11) NOT NULL DEFAULT -1,
  `charmEXP` smallint(6) NOT NULL DEFAULT -1,
  `pvpDamage` smallint(6) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

ALTER TABLE `mtsequipment`
  ADD PRIMARY KEY (`inventoryequipmentid`),
  ADD KEY `inventoryitemid` (`inventoryitemid`);
