CREATE TABLE IF NOT EXISTS `characters` (
  `id` int(11) NOT NULL,
  `accountid` int(11) NOT NULL DEFAULT 0,
  `world` tinyint(1) NOT NULL DEFAULT 0,
  `name` varchar(13) NOT NULL DEFAULT '',
  `level` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `exp` int(11) NOT NULL DEFAULT 0,
  `str` int(11) NOT NULL DEFAULT 0,
  `dex` int(11) NOT NULL DEFAULT 0,
  `luk` int(11) NOT NULL DEFAULT 0,
  `int` int(11) NOT NULL DEFAULT 0,
  `hp` int(11) NOT NULL DEFAULT 0,
  `mp` int(11) NOT NULL DEFAULT 0,
  `maxhp` int(11) NOT NULL DEFAULT 0,
  `maxmp` int(11) NOT NULL DEFAULT 0,
  `meso` int(11) NOT NULL DEFAULT 0,
  `hpApUsed` int(11) NOT NULL DEFAULT 0,
  `job` int(11) NOT NULL DEFAULT 0,
  `skincolor` tinyint(1) NOT NULL DEFAULT 0,
  `gender` tinyint(1) NOT NULL DEFAULT 0,
  `fame` int(11) NOT NULL DEFAULT 0,
  `hair` int(11) NOT NULL DEFAULT 0,
  `face` int(11) NOT NULL DEFAULT 0,
  `demonMarking` int(11) NOT NULL DEFAULT 0,
  `ap` int(11) NOT NULL DEFAULT 0,
  `map` int(11) NOT NULL DEFAULT 0,
  `spawnpoint` int(11) NOT NULL DEFAULT 0,
  `gm` int(11) NOT NULL DEFAULT 0,
  `party` int(11) NOT NULL DEFAULT 0,
  `buddyCapacity` int(11) NOT NULL DEFAULT 25,
  `createdate` timestamp NOT NULL DEFAULT current_timestamp(),
  `guildid` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `guildrank` tinyint(3) UNSIGNED NOT NULL DEFAULT 5,
  `allianceRank` tinyint(3) UNSIGNED NOT NULL DEFAULT 5,
  `guildContribution` int(11) NOT NULL DEFAULT 0,
  `pets` varchar(13) NOT NULL DEFAULT '-1,-1,-1',
  `sp` varchar(255) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0',
  `subcategory` int(11) NOT NULL DEFAULT 0,
  `rank` int(11) NOT NULL DEFAULT 1,
  `rankMove` int(11) NOT NULL DEFAULT 0,
  `jobRank` int(11) NOT NULL DEFAULT 1,
  `jobRankMove` int(11) NOT NULL DEFAULT 0,
  `marriageId` int(11) NOT NULL DEFAULT 0,
  `familyid` int(11) NOT NULL DEFAULT 0,
  `seniorid` int(11) NOT NULL DEFAULT 0,
  `junior1` int(11) NOT NULL DEFAULT 0,
  `junior2` int(11) NOT NULL DEFAULT 0,
  `currentrep` int(11) NOT NULL DEFAULT 0,
  `totalrep` int(11) NOT NULL DEFAULT 0,
  `gachexp` int(11) NOT NULL DEFAULT 0,
  `fatigue` tinyint(4) NOT NULL DEFAULT 0,
  `charm` mediumint(9) NOT NULL DEFAULT 0,
  `craft` mediumint(9) NOT NULL DEFAULT 0,
  `charisma` mediumint(9) NOT NULL DEFAULT 0,
  `will` mediumint(9) NOT NULL DEFAULT 0,
  `sense` mediumint(9) NOT NULL DEFAULT 0,
  `insight` mediumint(9) NOT NULL DEFAULT 0,
  `totalWins` int(11) NOT NULL DEFAULT 0,
  `totalLosses` int(11) NOT NULL DEFAULT 0,
  `pvpExp` int(11) NOT NULL DEFAULT 0,
  `pvpPoints` int(11) NOT NULL DEFAULT 0,
  `reborns` int(11) NOT NULL DEFAULT 0,
  `apstorage` int(11) NOT NULL DEFAULT 0,
  `claimedStarterKit` tinyint(1) NOT NULL default 0
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

--
-- Characters data.
--
INSERT IGNORE INTO `characters` (`id`, `accountid`, `world`, `name`, `level`, `exp`, `str`, `dex`, `luk`, `int`, `hp`, `mp`, `maxhp`, `maxmp`, `meso`, `hpApUsed`, `job`, `skincolor`, `gender`, `fame`, `hair`, `face`, `demonMarking`, `ap`, `map`, `spawnpoint`, `gm`, `party`, `buddyCapacity`, `createdate`, `guildid`, `guildrank`, `allianceRank`, `guildContribution`, `pets`, `sp`, `subcategory`, `rank`, `rankMove`, `jobRank`, `jobRankMove`, `marriageId`, `familyid`, `seniorid`, `junior1`, `junior2`, `currentrep`, `totalrep`, `gachexp`, `fatigue`, `charm`, `craft`, `charisma`, `will`, `sense`, `insight`, `totalWins`, `totalLosses`, `pvpExp`, `pvpPoints`, `reborns`, `apstorage`) VALUES
(18, 2, 0, 'Manu13', 15, 1489, 4, 4, 11, 71, 236, 408, 236, 378, 2147482497, 0, 200, 0, 0, 0, 30052, 20005, 0, 5, 910001000, 0, 7, -1, 20, '2021-06-12 23:06:41', 0, 5, 5, 0, '4,-1,-1', '3,0,0,0,0,0,0,0,0,0', 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

ALTER TABLE `characters`
  ADD PRIMARY KEY (`id`),
  ADD KEY `accountid` (`accountid`),
  ADD KEY `id` (`id`),
  ADD KEY `guildid` (`guildid`),
  ADD KEY `familyid` (`familyid`),
  ADD KEY `marriageId` (`marriageId`),
  ADD KEY `seniorid` (`seniorid`);